name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This line enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy files to the S3 bucket
      run: |
        aws s3 sync . s3://yumem.io --delete

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id E3EJOV83JCZDDD --paths "/*"
